image: node:20.12.0

cache:
  paths:
    - node_modules/

before_script:
  - npm install hexo-cli -g
  - npm install --force
  - hexo generate

pages:
  script:
    - hexo generate
  artifacts:
    paths:
      - public
  only:
    - master
